# pull the official base image
FROM python:3.9.5-alpine
# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1docker push marvinchebany94/oc_lettings_site:tagname
ENV PYTHONUNBUFFERED 1
# set work directory
RUN mkdir /app
WORKDIR /app
COPY ./requirements.txt .
COPY . .


RUN python -m venv env
RUN source env/bin/activate
RUN cd ..
RUN cd ..
# install dependencies
RUN pip install --upgrade pip

RUN apk update
RUN apk add postgresql-dev gcc python3-dev musl-dev
RUN pip install -r requirements.txt
EXPOSE 8000
CMD ['python', 'manage.py', 'collectstatic']
CMD ["python", "manage.py", "makemigrations"]
CMD ["python", "manage.py", "migrate"]
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]