# Generated by Django 4.0.2 on 2022-04-03 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0002_alter_address_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
